[2024-09-09T18:55:51.182] [ERROR] error - Error get agenda :  Error: Named replacement ":tgl_selesai" has no entry in the replacement map.
    at injectReplacements (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\utils\sql.ts:176:15)
    at Sequelize.query (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:612:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:164:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-09T18:55:51.183] [ERROR] error - Error: Named replacement ":tgl_selesai" has no entry in the replacement map.
    at injectReplacements (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\utils\sql.ts:176:15)
    at Sequelize.query (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:612:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:164:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-09T18:56:25.726] [ERROR] error - Error get agenda :  Error: Named replacement ":tgl_selesai" has no entry in the replacement map.
    at injectReplacements (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\utils\sql.ts:176:15)
    at Sequelize.query (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:612:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:164:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-09T18:56:25.732] [ERROR] error - Error: Named replacement ":tgl_selesai" has no entry in the replacement map.
    at injectReplacements (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\utils\sql.ts:176:15)
    at Sequelize.query (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:612:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:164:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-09T18:56:26.734] [ERROR] error - Error get agenda :  Error: Named replacement ":tgl_selesai" has no entry in the replacement map.
    at injectReplacements (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\utils\sql.ts:176:15)
    at Sequelize.query (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:612:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:164:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-09T18:56:26.735] [ERROR] error - Error: Named replacement ":tgl_selesai" has no entry in the replacement map.
    at injectReplacements (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\utils\sql.ts:176:15)
    at Sequelize.query (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:612:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:164:39
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2024-09-09T18:58:17.516] [ERROR] error - Error get agenda :  CustomError: Anda Belum Memiliki Agenda
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:180:46
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T18:58:17.521] [ERROR] error - CustomError: Anda Belum Memiliki Agenda
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:180:46
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T19:16:36.033] [ERROR] error - Error get agenda :  CustomError: Data Mahasiswa Tesis Tidak Ditemukan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:166:37
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T19:16:36.042] [ERROR] error - CustomError: Data Mahasiswa Tesis Tidak Ditemukan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:166:37
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T19:16:52.382] [ERROR] error - Error get agenda :  Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:52.404] [ERROR] error - Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:55.262] [ERROR] error - Error get agenda :  Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:55.263] [ERROR] error - Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:55.952] [ERROR] error - Error get agenda :  Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:55.953] [ERROR] error - Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:56.419] [ERROR] error - Error get agenda :  Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:16:56.420] [ERROR] error - Error: WHERE parameter "nidn" has invalid "undefined" value
    at MySQLQueryGenerator.whereItemQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2445:13)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2434:25
    at Array.forEach (<anonymous>)
    at MySQLQueryGenerator.whereItemsQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2432:35)
    at MySQLQueryGenerator.getWhereConditions (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:2860:19)
    at MySQLQueryGenerator.selectQuery (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-generator.js:1460:28)
    at MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1002:27)
    at Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:47)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12)
[2024-09-09T19:17:14.260] [ERROR] error - Error get agenda :  Error
    at Query.run (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at async Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:21)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  original: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
  parameters: {}
}
[2024-09-09T19:17:14.265] [ERROR] error - Error
    at Query.run (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at async Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:21)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  original: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
  parameters: {}
}
[2024-09-09T19:17:24.139] [ERROR] error - Error get agenda :  Error
    at Query.run (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at async Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:21)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  original: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
  parameters: {}
}
[2024-09-09T19:17:24.140] [ERROR] error - Error
    at Query.run (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at async Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:21)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  original: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
  parameters: {}
}
[2024-09-09T19:17:26.673] [ERROR] error - Error get agenda :  Error
    at Query.run (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at async Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:21)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  original: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
  parameters: {}
}
[2024-09-09T19:17:26.673] [ERROR] error - Error
    at Query.run (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
    at C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\sequelize.js:650:28
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MySQLQueryInterface.select (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\dialects\abstract\query-interface.js:1001:12)
    at async Function.findAll (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1824:21)
    at async Function.findOne (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\sequelize\src\model.js:1998:12) {
  name: 'SequelizeDatabaseError',
  parent: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  original: Error: Unknown column 'kode_status' in 'field list'
      at Packet.asError (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packets\packet.js:738:17)
      at Query.execute (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:481:34)
      at PacketParser.onPacket (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:97:12)
      at PacketParser.executeStart (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\mysql2\lib\connection.js:104:25)
      at Socket.emit (node:events:519:28)
      at Socket.emit (node:domain:488:12)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushByteMode (node:internal/streams/readable:510:3) {
    code: 'ER_BAD_FIELD_ERROR',
    errno: 1054,
    sqlState: '42S22',
    sqlMessage: "Unknown column 'kode_status' in 'field list'",
    sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
    parameters: undefined
  },
  sql: "SELECT `kode_status` FROM `ref_dospem` AS `RefDosepem` WHERE `RefDosepem`.`nidn` = '1';",
  parameters: {}
}
[2024-09-09T19:20:24.997] [ERROR] error - Error get agenda :  CustomError: Data Dosepem pembimbing Tesis Tidak Ditemukan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:232:37
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T19:20:25.002] [ERROR] error - CustomError: Data Dosepem pembimbing Tesis Tidak Ditemukan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:232:37
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\agenda.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T21:35:47.309] [ERROR] error - Error chect token :  CustomError: Unauthorized[0]
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:31:19
    at Generator.next (<anonymous>)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:4:12)
    at checkToken (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:25:78)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5) {
  code: 401,
  status: 'error'
}
[2024-09-09T21:35:47.315] [ERROR] error - CustomError: Unauthorized[0]
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:31:19
    at Generator.next (<anonymous>)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:4:12)
    at checkToken (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:25:78)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5) {
  code: 401,
  status: 'error'
}
[2024-09-09T21:35:51.103] [ERROR] error - Error chect token :  CustomError: Unauthorized[0]
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:31:19
    at Generator.next (<anonymous>)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:4:12)
    at checkToken (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:25:78)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5) {
  code: 401,
  status: 'error'
}
[2024-09-09T21:35:51.104] [ERROR] error - CustomError: Unauthorized[0]
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:31:19
    at Generator.next (<anonymous>)
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:4:12)
    at checkToken (C:\Users\irgyr\Documents\eksternal\si-moda\src\middleware\authorization.ts:25:78)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\irgyr\Documents\eksternal\si-moda\node_modules\express\lib\router\layer.js:95:5) {
  code: 401,
  status: 'error'
}
[2024-09-09T21:36:19.810] [ERROR] error - Error get daftar pertemuan :  CustomError: Anda Tidak Memiliki Agenda Bimbingan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:45:43
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T21:36:19.811] [ERROR] error - CustomError: Anda Tidak Memiliki Agenda Bimbingan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:45:43
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T23:40:23.916] [ERROR] error - Error get daftar pertemuan :  CustomError: Anda Tidak Memiliki Agenda Bimbingan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:45:49
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
[2024-09-09T23:40:23.924] [ERROR] error - CustomError: Anda Tidak Memiliki Agenda Bimbingan
    at C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:45:49
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\irgyr\Documents\eksternal\si-moda\src\controllers\web\agenda\daftar-pertemuan.controller.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 404,
  status: 'error'
}
